// ---------------------------------------------------------------------------
// trace-logo.mjs — trace the "J++ Device" wordmark to SVG paths from the real
// Outfit font (the font the logo is made in), so the mark is crisp vector art
// independent of webfont load. J++ is Outfit Black (900), Device is Regular
// (400), matching banner.webp. Run: npm run trace-logo
// ---------------------------------------------------------------------------
import opentype from 'opentype.js'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const fontsDir = path.join(root, 'node_modules/@fontsource/outfit/files')

function load(file) {
  const buf = fs.readFileSync(path.join(fontsDir, file))
  return opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
}

const black = load('outfit-latin-900-normal.woff') // J++
const regular = load('outfit-latin-400-normal.woff') // Device

const SIZE = 100 // em units → 1 em = 100 user units
const round = (n) => Math.round(n * 100) / 100

// Lay out "J++" (900) then a word space then "Device" (400) on one baseline.
const jpp = 'J++'
const device = 'Device'
const jppW = black.getAdvanceWidth(jpp, SIZE)
const spaceW = regular.getAdvanceWidth(' ', SIZE)
const deviceX = jppW + spaceW

const jppPath = black.getPath(jpp, 0, 0, SIZE)
const devicePath = regular.getPath(device, deviceX, 0, SIZE)

// Per-part bounding boxes (y is negative above the baseline).
const jBBox = black.getPath('J', 0, 0, SIZE).getBoundingBox()
const jppBBox = jppPath.getBoundingBox()
const fullBBox = {
  x1: Math.min(jppBBox.x1, devicePath.getBoundingBox().x1),
  y1: Math.min(jppBBox.y1, devicePath.getBoundingBox().y1),
  x2: Math.max(jppBBox.x2, devicePath.getBoundingBox().x2),
  y2: Math.max(jppBBox.y2, devicePath.getBoundingBox().y2),
}

// Cap height from the J (top is negative, baseline = 0).
const capTop = jBBox.y1
const capHeight = -capTop

// Yellow bar: same vertical extent as the J's cap height, and — per banner —
// its right edge sits ~0.42 cap-heights past the J's left edge (covering the
// left of the J). Left edge extends out as a signature highlight.
const barTop = capTop
const barBottom = 0
const barRight = round(jBBox.x1 + 0.42 * capHeight)
const barLeftBleed = round(jBBox.x1 - 1.35 * capHeight)

const out = {
  em: SIZE,
  capHeight: round(capHeight),
  jpp: { d: jppPath.toPathData(2), bbox: bbox(jppBBox) },
  device: { d: devicePath.toPathData(2), bbox: bbox(devicePath.getBoundingBox()) },
  full: bbox(fullBBox),
  bar: { top: round(barTop), bottom: barBottom, right: barRight, leftBleed: barLeftBleed },
}

function bbox(b) {
  return { x1: round(b.x1), y1: round(b.y1), x2: round(b.x2), y2: round(b.y2) }
}

const header = `// AUTO-GENERATED by scripts/trace-logo.mjs — do not edit by hand.
// Outfit Black (J++) + Outfit Regular (Device), traced to SVG paths.
`
fs.writeFileSync(
  path.join(root, 'src/assets/logo/logoPaths.js'),
  header + 'export const logo = ' + JSON.stringify(out, null, 2) + '\n\nexport default logo\n'
)

// Standalone favicon: J++ (black) on a yellow rounded square.
const jOnly = black.getPath('J++', 0, 0, SIZE)
const jb = jOnly.getBoundingBox()
const pad = capHeight * 0.34
const vx = round(jb.x1 - pad)
const vy = round(jb.y1 - pad)
const vw = round(jb.x2 - jb.x1 + pad * 2)
const vh = round(jb.y2 - jb.y1 + pad * 2)
const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vx} ${vy} ${vw} ${vh}">
  <rect x="${vx}" y="${vy}" width="${vw}" height="${vh}" rx="${round(vw * 0.16)}" fill="#fdf254"/>
  <path d="${jOnly.toPathData(2)}" fill="#1a1a1a"/>
</svg>
`
fs.writeFileSync(path.join(root, 'public/favicon.svg'), favicon)

console.log('wrote src/assets/logo/logoPaths.js and public/favicon.svg')
console.log('cap height:', out.capHeight, 'bar right:', out.bar.right, 'J bbox:', out.jpp.bbox)
